name: DevOps_la01
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Rodando meu Build
      run: echo Build deu bom
      
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Rodando me deploy
      run: echo Deploy Dev deu bom
  deploy-hml:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
    - name: Rodando meu deploy
      run: echo Deploy HML deu bom
  deploy-sast:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Rodando meu deploy sast
      run: echo Deploy sast deu bom
